import BlogImg from "../../assets/images/blogimg.png";

export const BlogData = [
  {
    id: 1,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 2,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 3,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 4,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 5,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 6,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 7,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 8,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 9,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
  {
    id: 10,
    blogimg: `${BlogImg}`,
    title: "Lottery changed my life- Local Trader.",
    body: `Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees. Hello rock empire Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders Have you got kids or siblings in elementary or secondary school? The most important resource we have is our children since they are our future. Let’s support you in making provisions for our future leaders,
    The Rock Empire is giving a year’s worth of tuition fees to pupils, isn’t it exciting?The single most significant contribution, in my opinion, is making early educational investments in our kids. Every child has a rainbow inside them yearning to shine, and education is the key to success. It takes a big heart to help the little ones.
    Have you seen the viral video of a young girl who chose to be caned over being sent home for not paying her school fees? The girl in the video goes by the name Success and was a student at a particular school in Delta. She insisted on attending school no matter what, even if it meant being flogged for not paying her fees`
  },
];
